development:
  dialect: postgres
  datasource: host=localhost port=5432 user=root password=root dbname=talad sslmode=disable
  dir: migrations/postgres
  table: migrations

staging:
  dialect: postgres
  datasource: host=139.5.147.215 port=5432 user=pgkad password=pgkad dbname=cnxdb sslmode=disable
  dir: migrations/postgres
  table: migrations

# production:
#   dialect: postgres
#   datasource: dbname=c9db sslmode=disable
#   dir: migrations/postgres
#   table: migrations