development:
  dialect: postgres
  datasource: host=localhost port=5432 user=root password=root dbname=db sslmode=disable
  dir: migrations/postgres
  table: migrations

staging:
  dialect: postgres
  datasource: host=ip port=5432 user=xxx password=xxx dbname=xxx sslmode=disable
  dir: migrations/postgres
  table: migrations

# production:
#   dialect: postgres
#   datasource: dbname=db sslmode=disable
#   dir: migrations/postgres
#   table: migrations
